name: dartling_datagrid
version: 0.0.1
author: David Curtis
description: dartling_datagrid application that uses dartling for its model.
homepage: http://ondart.me/
dependencies:
  browser: any
  web_ui: any
  dartling_list_generator:
    git: git://github.com/davidcurtis/dartling_list_generator.git
  dartling:
    git: git://github.com/dzenanr/dartling.git
